### ISSUE TITLE
Question: which Python 3 version does psycogreen support?

### ISSUE THREAD

**Issue by andreagrandi** [psycopg/psycogreen#1]
Hi 👋

I'm about to upgrade an existing project running on Python 3.5 to a more recent version of Python (initially **Python 3.6** but the plan is to migrate to the latest at later time).

Since `psycogreen` is one of the project's dependencies, I was wondering which versions of Python 3 are currently supported. I could not find any specific references in the `setup.py` nor in any other configuration file.

Thanks 🙌

**Comment by dvarrazzo** [comment]
Ciao @andreagrandi 

They are all supported. If they aren't they can be supported easily: psycogreen mostly consists of 2-3 simple function allowing psycopg to interact with the I/O completion strategy of your application, and nothing about it has inherent problems with any specific Python version.

Said so, feel free to run the test suite and let us know if you find any failure.

Cheers

-- Daniele
