### ISSUE TITLE
psycogreen breaks connect_timeout option

### ISSUE THREAD

**Issue by redlolgeerf** [psycopg/psycogreen#2]
python version 3.8.6

library versions:
gevent==20.9.0
greenlet==0.4.17
psycogreen==1.0.2
psycopg2==2.8.6

minimal example:
```
import gevent
import gevent.monkey

gevent.monkey.patch_all()  # noqa

import psycogreen.gevent

psycogreen.gevent.patch_psycopg()  # noqa

import psycopg2


def fetch(num, secs):
    print("connecting to db")
    conn = psycopg2.connect("dbname=postgres connect_timeout=1")
    print("connected")


jobs = [gevent.spawn(fetch, 3, 2)]
gevent.joinall(jobs)
```
This will print "connecting to db" and hang. If you comment out line `psycogreen.gevent.patch_psycopg()  # noqa` code will fail with OperationalError in couple seconds.

**Comment by redlolgeerf** [comment]
Desired behavior can be achieved, if I replace `psycogreen.gevent.patch_psycopg()` with 
```
from psycogreen.gevent import gevent_wait_callback
from psycopg2 import extensions
from functools import partial
extensions.set_wait_callback(partial(gevent_wait_callback, timeout=1))
```
Maybe, this should be added to documentation.

**Comment by dvarrazzo** [comment]
Yes, I'm aware: in async mode the libpq doesn't respect the connect_timeout, it is the client which should re-implement it. So this is actually a psycopg2 problem. There might be a ticket open for it already... yup, this: https://github.com/psycopg/psycopg2/issues/944

**Comment by redlolgeerf** [comment]
Thanks, I'll close this issue then.
