### ISSUE TITLE
question: integration with django / examples

### ISSUE THREAD

**Issue by benzkji** [psycopg/psycogreen#4]
as mentioned here:  
https://serverfault.com/questions/635100/django-conn-max-age-persists-connections-but-doesnt-reuse-them-with-postgresq

I am a bit lost, and wonder if there are any examples, showing an django intergration with psycogreen. As I interpret, it could be a drop in solution, that could make for example pgbouncer no more necessary, when using geven/eventlet. The key question for me: Where to do the monkey patching? in the .wsgi file? Other places?

**Comment by dvarrazzo** [comment]
What you link is 7 years old, I don't know how valid it is.

The question you ask is something between Django and eventlet or gevent. You should check with those project what is the best place if you want to use them together.
