### ISSUE TITLE
Psycopg3 support

### ISSUE THREAD

**Issue by elderlabs** [psycopg/psycogreen#5]
Now that [psycopg3](https://github.com/psycopg/psycopg) exists, are there plans to add support for it? I'm one to assume support for psycopg2 will be in decline in the coming months.

Thanks.

**Comment by dvarrazzo** [comment]
Psycopg 3 is always in "green mode", it only uses non-blocking c functions. The wait code of Psycopg 3 and its locks are in python, even when the c extension is used. So I do t think there is such need: normal eventlet/gevent monkeypatching should work.

If it doesn't we can fix things, but there isn't a need of a wait helper.

**Comment by elderlabs** [comment]
Thank you for the prompt response and clarification!

**Comment by dvarrazzo** [comment]
Note that I haven't done a lot of experimentation with either gevent or eventlet and psycopg 3. If you would like to test (for instance trying to run the test suite using a greenlet library) it would be good to know and either fix problems or add documentation.
