### ISSUE TITLE
Documentation update for psycopg 3 gevent

### ISSUE THREAD

**Issue by maybephilipp** [psycopg/psycogreen#8]
Please update the doc mentioning that psycopg (aka psycopg 3) doesn't require this module since has built-in support of gevent. See https://github.com/psycopg/psycopg/issues/4#issuecomment-633166065

**Comment by dvarrazzo** [comment]
Not quite: psycopg 3 may require it when using the C extension. This module should actually introduce its support.

**Comment by dvarrazzo** [comment]
Added #9.
